config/routes.rb
Rails.application.routes.draw do
  resources :jobtips
  mount Ckeditor::Engine => '/ckeditor'
  resources :talents
  resources :companies
  resources :articles
  resources :jobs

  root 'landing#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :image, styles: { :medium => "318x180", :small => "241x200", :large => "800x500"}
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :slider]

  # GET /articles
  # GET /articles.json
  def slider
     @articles = Article.all
  end


  def index
    @articles = Article.all
    @jobtips = Jobtip.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :image, :short_desc)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
<%= f.error_notification %>
Post New Article
   <%= f.input :title %>
   <%= f.input :short_desc %>
   <%= f.cktext_area :description %>
   <%= f.file_field :image, as: :file %>
   <%= f.button :submit %> 
<% end %>      

app/views/articles/_latestarticles.html.erb
<div class="card hoverable ">
   <div class="card-content">
      <span class="card-title">Latest Article</span>
      <% @articles.each do |article| %>
      <li><%= link_to article.title,article %> posted at <cite><%= article.created_at.strftime('%a %b %d ') %></cite></li>
      <%end%>  
    </div>
    <div class="card-action">
       <a href="#">This is a link</a>
  
    </div>
</div>

app/views/articles/_slider.html.erb
<div class="slider">
    <ul class="slides">
      <% @articles.each do |article| %>
     <li>
        <%= image_tag article.image.url(:large) %> <!-- random image -->
        <div class="caption left-align">
          <h5><%= link_to article.title,article, class: "white-text" %></h5>
          <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

app/views/articles/edit.html.erb
<div class="container">
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col s12 m8">    
<%= render 'slider' %>
<% @articles.each do |article| %>
     <div class="card z-depth-1 hoverable ">
   	 	<h4 class="center-align"><%= link_to article.title,article %></h4>
     	<div class="card-content"><%= article.short_desc %></div>
        <%= link_to 'Edit', edit_article_path(article) %>
     	<%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
     	<%= link_to 'New article', new_article_path %>
 	 </div>
<% end %>
</div>

<div class="col s12 m4">   
<h5> JOBS Tips </h5>
<% @jobtips.each do |jobtip| %>
     <div class="card z-depth-1 hoverable ">
     <div class="card-image">
     	<%= image_tag jobtip.image.url(:medium) %>
     	<span class="card-title"><%= link_to jobtip.title,jobtip %></span>
     </div>	
   	 	<div class="card-content">Content : sek, belum dibikin method nya</div>
        <%= link_to 'Edit', edit_jobtip_path(jobtip) %>
     	<%= link_to 'Destroy', jobtip, method: :delete, data: { confirm: 'Are you sure?' } %>
     	<%= link_to 'New article', new_jobtip_path %>
 	 </div>
<% end %>
</div>


</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <h5 class='text-center'>Article </h5>
   		<hr>
      </h4>
    </div>
  </div>
<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

Article 
<div class="card z-depth-3 "  >
	<div class="card-image">
  		<%= image_tag @article.image.url(:large) %>
    	<span class="card-title"><%= @article.title %></span>
    </div>
    <div class="card-content"><%= @article.description.html_safe %></div>
  	 <%= link_to 'Edit', edit_article_path(@article) %> 
	 <%= link_to 'Back', articles_path %>
  	</div>
</div>