config/routes.rb
Rails.application.routes.draw do
  resources :jobtips
  mount Ckeditor::Engine => '/ckeditor'
  resources :talents
  resources :companies
  resources :articles
  resources :jobs

  root 'landing#index'

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  @articles = Article.all.order("created_at DESC")
  @jobs = Job.all.order("created_at DESC")
  @talents = Talent.all.order("created_at DESC")
  end


end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/_nav.html.erb
  <nav>
    <div class="nav-wrapper">
      <a class="brand-logo"><%= link_to 'TechjobsinJOGJA', root_path %></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a> <%= link_to 'Home', root_path %></a></li>
        <li> <%= link_to 'Jobs', jobs_path %> </li>
        <li> <%= link_to 'Article', articles_path %> </li>
        <li> <%= link_to 'Company', companies_path %> </li>
        <li> <%= link_to 'About Us', root_path %> </li>
      </ul>
    </div>
  </nav>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li> <%= link_to 'Jobs', jobs_path %> </li>
        <li> <%= link_to 'Article', articles_path %> </li>
        <li> <%= link_to 'Company', companies_path %> </li>
        <li> <%= link_to 'About Us', root_path %> </li>
    </ul>
 

app/views/landing/index.html.erb
<br>
<br>
<div class="row">
	<div class="col s12 m6">
		<img><%= image_tag "logoasli.png", class: "right" %></img>
	</div>
	<div class="col s12 m6">
	<br>
		<h6 class="left-align">"Not all those who wander are lost" </h6>
		<h6 class="left-align"><cite title="Source Title">J. R. R. Tolkien ~ Lord of The Ring</cite></h6>
		<h5 class="left-align">YOUR JOURNEY STARTS <%= link_to 'HERE', jobs_path %></h5>
	</div>
</div>
<br>
<div class="container">
  <nav>
    <div class="nav-wrapper">
      <form>
        <div class="input-field">
          <input id="search" type="search" required>
          <label for="search"><i class="material-icons">search</i></label>
          <i class="material-icons">close</i>
        </div>
      </form>
    </div>
  </nav>
</div>

<br>

    <div class="row">
        <div class="col s12 m4">
		  <%= render 'articles/latestarticles' %>
		</div>
		<div class="col s12 m4"> 
	      <%= render 'jobs/latestjobs' %>
	    </div>
	    <div class="col s12 m4"> 
	      <%= render 'talents/newtalents' %>
	    </div>
	</div>