config/routes.rb
Rails.application.routes.draw do
  resources :jobtips
  mount Ckeditor::Engine => '/ckeditor'
  resources :talents
  resources :companies
  resources :articles
  resources :jobs

  root 'landing#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    @companies = Company.all.order("created_at DESC")
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :company, :url, :salary, :short_content)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>
   <div class="form-group">
      <%= f.input :title %>
      <%= f.input :short_content %>
      <%= f.cktext_area :description %>
      <%= f.input :company %>
      <%= f.input :url %>
      <%= f.input :salary %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/jobs/_latestjobs.html.erb
<div class="card hoverable">
   <div class="card-content">
      <span class="card-title">Latest JOBS</span>
      <% @jobs.each do |job| %>
      <li><%= link_to job.title,job %> posted at <cite><%= job.created_at.strftime('%a %b %d ') %></cite></li>
      <%end%>  
    </div>
    <div class="card-action">
       <a href="#">This is a link</a>
   
    </div>
</div>

app/views/jobs/edit.html.erb
<div class="container-fluid">
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>


<h5 class='text-center'>Jobs Opening</h5>
<div class="row">
<div class="col s12 m8">
<% @jobs.each do |job| %>
    <div class="card z-depth-1 hoverable "  >
        <h4 class="center-align"><%= link_to job.title,job %> at <%= job.company %></h3>
        <div class="card-content">
        <p><%= job.short_content %></p>
        <p class="card-text">Salary : <%= job.salary %></p>
        
        <p class="card-text"><h6 class="right-align"><%= job.created_at.strftime('%a %b %d ') %></h6></p>
   		</div>
   		<td><%= link_to 'Show', job %></td>
		<td><%= link_to 'Edit', edit_job_path(job) %></td>
		<td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<%= link_to 'New Job', new_job_path %>
  
    </div>
<% end %>
</div>

<div class="col s12 m4">
<%= render 'companies/companyrandom' %>
</div>
	



</div>

app/views/jobs/new.html.erb
<div class="container">
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Shout:</strong>
  <%= @job.short_content %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description.html_safe %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Url:</strong>
  <%= @job.url %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>